name: flutter_template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dartz: ^0.10.1
  dio: ^5.8.0+1
  email_sanity: ^0.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_gen: ^5.10.0
  flutter_hooks: ^0.21.2
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  shadcn_ui: ^0.22.5
  skeletonizer: ^1.4.3

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  json_serializable: ^6.9.4

flutter_gen:
  output: lib/app/config/res/gen/ # Optional (default: lib/gen/)
  # integrations:
  #   lottie: true
  #   flutter_svg: true
  colors:
    inputs:
      - assets/colors.xml
  assets:
    exclude:
      - .env

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
